# Generated by Django 4.2.9 on 2024-02-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
    ]
